# Generated by Django 5.0.2 on 2024-02-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_token_created_alter_token_key_alter_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
